management:
  endpoint:
    health:
      enabled: true
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:

orderjoin:
  environmentId: ${ENV_ID:dev}
  applicationId: ${APPLICATION_ID:orderjoin}
  trusted-packages: "com.order.join.*"
  raw-topic: "${RAW_TOPIC:order.raw}"
  auto-offset-reset: "earliest"
