name: dexcom-java-component-build-ci

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'harness-deploy/**'
      - 'README.md'
      - '.github/**'
      - '.gitignore'
  workflow_dispatch:  

jobs:
  build:
    name: Java Component Build
    uses: dexcomit/github-workflows/.github/workflows/java-component-build.yml@master
    with:
      componentName: 'it-oms-order-service'
      componentBaseVersion: '1.0.1'
      gradle-version: 7.5.1
      java-version: 17
